### ISSUE TITLE
maybe broken!?

### ISSUE THREAD

**Issue by HansHammel** [bruderstein/gulp-html-src#3]
For some curious reason no error occurs, but it doesn't output anything. I tested against bare output and the competitor gulp-dom-src. Both work for me in a rather complex scenario perhaps (in my case) scripts with/without src-attribute and different types e.g. text/ng-template or html-partials may cause this issue...

**Comment by bruderstein** [comment]
Can you provide a sample HTML source that doesn't work?

**Comment by bruderstein** [comment]
Closing as no sample provided (if you can get back with some sample html where it doesn't work, I'll happily reopen the issue and fix it)
