### ISSUE TITLE
Get scripts/css only inside some unique tags

### ISSUE THREAD

**Issue by SyntaxRules** [bruderstein/gulp-html-src#4]
I'd like to get all of my script tags with my `index.html` file that are within a certain section of it.

For example a portion of an index file might look like:
```javascript
<script src="foo.js"></script>
<script src="foo1.js"></script>

<!-- gulp-html-src identifier -->
<script src="bar.js"></script>
<script src="bar1.js"></script>
<!-- end gulp-html-src -->
```

I'd like to run `gulp-html-src` and get just `bar.js' and `bar1.js`. Perhaps the grunt task could look like this:
```javascript
gulp.src('./src/index.html')
        .pipe(ghtmlSrc({ 
                   token: 'identifier' 
        }))
        //Using the example above this returns bar.js, bar1.js
        .pipe(uglify())
        .pipe(gulp.dest('./build/'));
```

Does functionality like this already exist? Would it be possible to add it to existence?

**Comment by bruderstein** [comment]
Not at the moment - it's purely selector based, so you'd need to mark the individual scripts, I think, in order to use it like this.

``` html
    <script src="foo.js"></script>
    <script src="foo1.js"></script>


    <script src="bar.js" data-html-src></script>
    <script src="bar1.js" data-html-src></script>
```

And then use the data-html-src attribute in the selector:

``` javascript
    gulp.src('./src/index.html')
        .pipe(ghtmlSrc({
              selector: 'script[data-html-src]'
        })
       .pipe(uglify())
       .pipe(gulp.dest('./build/'))

```

Maybe you can come up with something cleverer so you can use start and end markers, but I can't think how you could do that.
